### ISSUE TITLE
"The IPSec Shared Secret is missing"

### ISSUE THREAD

**Issue by z-akira** [stve/alfred-vpn#4]
I get the following message in my Mac. 

"The IPSec Shared Secret is missing. Verify your settings and try reconnecting."

My OS is High Sierra.

Any idea why?

**Comment by zitscher** [comment]
I have the same issue. Any new insights?

**Comment by punkstar** [comment]
The command used in this workflow is `scutil`. Looking at the docs for the `scutil --nc start` command that it uses, you need to pass in credentials to the command:

```
scutil --nc help

...

	start <service> [--user user] [--password password] [--secret secret]
		Start a given service. Can take optional arguments for user, password, and secret
```

Not sure how you'd change this workflow to get it working but this is probably the problem.

**Comment by indigoblueraspberry** [comment]
I solved this problem with workaround by using an applescript.

Step 1: Create an applescript - startVPN.scpt
```
on run argv
    set MyVPNName to item 1 of argv

    tell application "System Events"
        tell current location of network preferences
                set myConnection to the service MyVPNName
                if myConnection is not null then
                        if current configuration of myConnection is not connected then
                                connect myConnection
                        end if
                end if
        end tell
    end tell
end run
```

Adapted script from: https://blog.timac.org/2018/0719-vpnstatus/

Step 2: Modify utils.js in the alfred workflow, which is most likely located in a similar path on your machine ../node_modules/alfred-vpn/src/utils.js
```
exports.Connect = name => {
	return spawn('osascript', ['/path/to/startVPN.scpt', name]);
};
```

**Comment by larkov** [comment]
You can also change utils.js to use below code so that you don't need an additional file.

```
exports.Connect = name => {
  return spawn('osascript', ['-e',
    `on run argv
    set MyVPNName to item 1 of argv

    tell application "System Events"
      tell current location of network preferences
        set myConnection to the service MyVPNName
        if myConnection is not null then
          if current configuration of myConnection is not connected then
            connect myConnection
          end if
        end if
      end tell
    end tell
  end run`,
  name]);
};
```

I'll also make this as a pull request to the repo.
